// // TASKS
export const LIST_TASKS = 'LIST_TASKS';

// PATIENTS
export const LIST_PATIENTS = 'LIST_PATIENTS';

// MISC
export const LIST_HOSPITALS = 'LIST_HOSPITALS';
export const LIST_PATHOLOGIES = 'LIST_PATHOLOGIES';
export const LIST_EMERGENCY_SERVICES = 'LIST_EMERGENCY_SERVICES';
export const LIST_PARTNER_SERVICE = 'LIST_PARTNER_SERVICE';
