// // TASKS
export const LIST_TASKS = 'LIST_TASKS';
export const CLEAR_TASKS = 'CLEAR_TASKS';

// PATIENTS
export const LIST_PATIENTS = 'LIST_PATIENTS';
export const CLEAR_PATIENTS = 'CLEAR_PATIENTS';

// MISC
export const LIST_HOSPITALS = 'LIST_HOSPITALS';
export const LIST_PATHOLOGIES = 'LIST_PATHOLOGIES';
export const LIST_EMERGENCY_SERVICES = 'LIST_EMERGENCY_SERVICES';
export const LIST_PARTNER_SERVICE = 'LIST_PARTNER_SERVICE';

export const CLEAR_HOSPITALS = 'CLEAR_HOSPITALS';
export const CLEAR_PATHOLOGIES = 'CLEAR_PATHOLOGIES';
export const CLEAR_EMERGENCY_SERVICES = 'CLEAR_EMERGENCY_SERVICES';
export const CLEAR_PARTNER_SERVICE = 'CLEAR_PARTNER_SERVICE';
